Win8Apps/Controllers/AppsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using Raven.Abstractions.Data;
using Raven.Client;
using Raven.Client.Linq;
using Win8Apps.Extensions;
using Win8Apps.Indexes;
using Win8Apps.Model;
using Win8Apps.Model.Boost;
using Win8Apps.Models;
using Facet = Win8Apps.Model.Facet;

namespace Win8Apps.Controllers
{
    public class AppsController : RavenDbController
    {

        public ActionResult Featured(int count = 10)
        {
            var featuredApps = DocumentSession
                .Load<AppsList>("AppsLists/1");

            var apps = DocumentSession
                .Load<App>(featuredApps.Apps.RandomSample(count));

            Debug.Assert(apps.All(a => a != null));

            return PartialView("ListApps", apps.Where(a => a != null));
        }

        public ActionResult Recent(int count = 21)
        {
            var apps = DocumentSession.Query<App, Apps_ByLastUpdated>()
                                      .OrderByDescending(a => a.LastUpdated)
                                      .Take(count);

            return View("AppsPage", new AppsPage
                {
                    PageTitle = "Recently updated apps",
                    Apps = apps
                });
        }

        public ActionResult GoneFree(int count = 21)
        {
            var apps = DocumentSession.Query<App>("Apps/GoneFree")
                .OrderByDescending(a => a.LastUpdated)
                .Take(count);

            return View("AppsPage", new AppsPage
            {
                PageTitle = "Apps gone free",
                Apps = apps
            });
        }

        public ActionResult TopGames(int count = 21)
        {
            var apps = DocumentSession.Query<App>("Apps/ByCategoryAndPrice")
                                      .Where(a => a.Category.Id == CategoryIds.Games)
                                      .OrderByDescending(a => a.ScoreRating)
                                      .Take(count)
                                      .ToList();

            return View("AppsPage", new AppsPage
                {
                    PageTitle = "Top games",
                    Apps = apps
                });
        }

        public ActionResult TopFreeGames(int count = 21)
        {
            var games = DocumentSession.Query<App>("Apps/ByCategoryAndPrice")
                .Where(a => a.Category.Id == CategoryIds.Games);
            var freeGames = games.Where(a => a.Price.Amount == 0.0f);
            var sortedFreeGames = freeGames.OrderByDescending(a => a.ScoreRating);
            var apps = sortedFreeGames.Take(count).ToList();

            return View("AppsPage", new AppsPage
                {
                    PageTitle = "Top free games",
                    Apps = apps
                });
        }

        public ActionResult TopApps(int count = 21)
        {
            var apps = DocumentSession.Query<App>("Apps/ByCategoryAndPrice")
                                      .Where(a => a.Category.Id != CategoryIds.Games)
                                      .OrderByDescending(a => a.ScoreRating)
                                      .Take(count)
                                      .ToList();

            return View("AppsPage", new AppsPage
                {
                    PageTitle = "Top apps",
                    Apps = apps
                });
        }

        public ActionResult TopFreeApps(int count = 21)
        {
            var apps = DocumentSession.Query<App>("Apps/ByCategoryAndPrice")
                                      .Where(a => a.Category.Id != CategoryIds.Games)
                                      .Where(a => a.Price.Amount == 0.0f)
                                      .OrderByDescending(a => a.ScoreRating)
                                      .Take(count)
                                      .ToList();

            return View("AppsPage", new AppsPage
                {
                    PageTitle = "Top free apps",
                    Apps = apps
                });
        }

        public ActionResult Topics()
        {
            var topics = DocumentSession.Query<AppsList>()
                               .Where(t => !t.IsFeatured)
                               .OrderByDescending(t => t.LastDateSeen)
                               .ToList();

            return View("Topics", topics);
        }

        public ActionResult Topic(string topicId)
        {
            var topic = DocumentSession
                .Include<AppsList>(t => t.Apps)
                .Load<AppsList>(topicId);

            if (topic == null)
            {
                Response.StatusCode = 404;
                Response.StatusDescription = "The requested topic was not found";
                return View("Topic", null);
            }

            var apps = DocumentSession.Load<App>(topic.Apps);

            return View("Topic", new TopicViewModel
                {
                    Topic = topic, 
                    Apps = apps.Where(a => a != null)
                });
        }

        public ActionResult Categories()
        {
            var categories = Enum.GetValues(typeof (CategoryIds))
                                 .Cast<CategoryIds>()
                                 .Select(c => new CategoryDescription {Id = c, Title = c.GetDescription()})
                                 .Where(c => c.Title != null);

            return PartialView(categories);
        }

        public ActionResult App(string id)
        {
            Guid appId;
            App app;
            if (Guid.TryParse(id, out appId))
                app = DocumentSession.Load<App>("apps/" + id);
            else
            {
                app = DocumentSession.Query<App>()
                    .FirstOrDefault(a => a.FriendlyUrl == id);
            }

            if (app == null)
            {
                Response.StatusCode = 404;
                Response.StatusDescription = "The requested app was not found";
                return View("AppNotFound");
            }

            return View(app);
        }

        public ActionResult Search(string query, int page = 1, string ageRating = null, string developer = null,
                                   string category = null, string subCategory = null, string country = null,
                                   string language = null, string sortBy = null, SortOrder sortOrder = SortOrder.Desc)
        {
            if (string.IsNullOrEmpty(query))
                query = string.Empty;

            RavenQueryStatistics statistics;
            var q = DocumentSession
                .Query<Apps_Search2.Result, Apps_Search2>()
                .Statistics(out statistics);

            if (!string.IsNullOrEmpty(query))
                q = q.Search(x => x.Query, query);

            q = BoostMethod(q);
           
            
            var filters = new List<FilterViewModel>();
            
            if (!string.IsNullOrEmpty(ageRating))
            {
                q = q.Where(x => x.AgeRating == ageRating);
                filters.Add(new FilterViewModel
                    {
                        DisplayText = string.Format("Age Rating: {0}", ageRating),
                        Query = "ageRating"
                    });
            }
            if (!string.IsNullOrEmpty(developer))
            {
                q = q.Where(x => x.Developer == developer);
                filters.Add(new FilterViewModel
                {
                    DisplayText = string.Format("Developer: {0}", developer),
                    Query = "developer"
                });
            }
            if (!string.IsNullOrEmpty(category))
            {
                q = q.Where(x => x.Category == category);
                filters.Add(new FilterViewModel
                {
                    DisplayText = string.Format("Category: {0}", category),
                    Query = "category"
                });
                
            }
            if (!string.IsNullOrEmpty(subCategory))
            {
                q = q.Where(x => x.Subcategory == subCategory);
                filters.Add(new FilterViewModel
                {
                    DisplayText = string.Format("Sub Category: {0}", subCategory),
                    Query = "subCategory"
                });
            }
            if (!string.IsNullOrEmpty(country))
            {
                q = q.Where(x => x.Country.Any(c => c == country));
                filters.Add(new FilterViewModel
                {
                    DisplayText = string.Format("Country: {0}", country),
                    Query = "country"
                });
            }
            if (!string.IsNullOrEmpty(language))
            {
                q = q.Where(x => x.Language == language);
                filters.Add(new FilterViewModel
                {
                    DisplayText = string.Format("Language: {0}", language),
                    Query = "language"
                });
            }

            ViewBag.sortOrder = sortOrder;
            SortBy sortByOrder;
            if (Enum.TryParse(sortBy, true, out sortByOrder))
            {
                Expression<Func<Apps_Search2.Result, object>> keySelector = null;
                if (sortByOrder == SortBy.Category)
                     keySelector = r => r.Category;
                else if (sortByOrder == SortBy.Language)
                    keySelector = r => r.Language;
                else if (sortByOrder == SortBy.Price)
                    keySelector = r => r.Price;
                else if (sortByOrder == SortBy.ScoreRating)
                    keySelector = r => r.ScoreRating;
                else if (sortByOrder == SortBy.Title)
                    keySelector = r => r.Title;

                if (keySelector != null)

Win8Apps/Controllers/StatsController.cs
using System.Linq;
using System.Web.Mvc;
using Raven.Abstractions.Data;
using Raven.Client;
using Win8Apps.Indexes;
using Win8Apps.Model;
using Win8Apps.Model.Indexes;

namespace Win8Apps.Controllers
{
    public class StatsController : RavenDbController
    {
        public const string StatsFacetsKey = "StatsFacets";
        public ActionResult Index()
        {
            return null;
        }

        public ActionResult Developers()
        {
            TempData[StatsFacetsKey] = CalcStatisticsFacet();
            return View();
        }

        public ActionResult Apps()
        {
            TempData[StatsFacetsKey] = CalcStatisticsFacet();
            return View();
        }

        public ActionResult Overview()
        {
            TempData[StatsFacetsKey] = CalcStatisticsFacet();
            return View();
        }

        private FacetResults CalcStatisticsFacet()
        {
            var query = DocumentSession
                .Query<App>("Apps/Stats");

            var facetResults = query.ToFacets("facets/StatsFacets");
            //FixRanges(facetResults);

            return facetResults;
        }

        public ActionResult TopDevelopers()
        {
            var result = DocumentSession.Query<Developers_AppsCount.ReduceResult, Developers_AppsCount>()
                                        .OrderByDescending(r => r.Count)
                                        .ThenBy(r => r.Developer)
                                        .Take(100);
            return PartialView(result);
        }


        public ActionResult AppsByCategory()
        {
            var facetResults = TempData[StatsFacetsKey] as FacetResults;
            return PartialView(facetResults.Results["Category"].Values);
        }

        public ActionResult AppsByPlatform()
        {
            var facetResults = TempData[StatsFacetsKey] as FacetResults;
            return PartialView(facetResults.Results["SupportedPlatforms"].Values);
        }

        public ActionResult AppsByLanguage()
        {
            var facetResults = TempData[StatsFacetsKey] as FacetResults;
            return PartialView(facetResults.Results["Language"].Values);

        }

        public ActionResult AppsByRatingRange()
        {
            var result = DocumentSession.Query<Apps_RatingRange.ReduceResult, Apps_RatingRange>()
                                        .OrderByDescending(r => r.Rating)
                                        .Take(100);

            return PartialView(result);
        }

        public ActionResult AppsByDate()
        {
            var stats = DocumentSession.Query<Stat>()
                .OrderBy(x => x.Date)
                .ToList();

            return PartialView(stats);
        }

        public ActionResult DevByDate()
        {
            var stats = DocumentSession.Query<Stat>()
                .OrderBy(x => x.Date)
                .ToList();

            return PartialView(stats);
        }
    }
}

Win8Apps/Views/shared/_BootstrapLayout.basic.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="target-densitydpi=device-dpi, width=device-width, initial-scale=1.0, maximum-scale=1">
    <meta name="description" content="WinApps - Windows Store alternative">
    <meta name="author" content="Itay Sagui; Ariel Ornstein">
    <meta name="keywords" content="windows 8, modern, Windows Store, apps, applications">
    
    <link rel="icon" href="~/favicon.ico">
    <link rel="shortcut icon" href="~/favicon.ico">


    <meta name="msApplication-tooltip" content="WinApps - Windows Store alternative" />
    <meta name="msApplication-starturl" content="./" />
    <meta name="msApplication-window" content="width=1024;height=768" />
    <meta name="msApplication-navbutton-color" content="#2d89ef" />
    
    <meta name="msApplication-task" content="name=Games;action-uri=.@Url.Action("Search", "Apps", new { category = "Games" });icon-uri=./favicon.ico" />
    <meta name="msApplication-task" content="name=Social;action-uri=.@Url.Action("Search", "Apps", new { category = "Social" });icon-uri=./favicon.ico" />
    <meta name="msApplication-task" content="name=Photo;action-uri=.@Url.Action("Search", "Apps", new { category = "Photo" });icon-uri=./favicon.ico" />
    <meta name="msApplication-task" content="name=Education;action-uri=.@Url.Action("Search", "Apps", new { category = "Education" });icon-uri=./favicon.ico" />

    <meta name="msApplication-task-separator" content="" />
    <meta name="msApplication-task" content="name=Statistics;action-uri=.@Url.Action("Overview", "Stats");icon-uri=./favicon.ico" />
    
    @if (@ViewBag.Title != null)
    {
        <title>@ViewBag.Title</title>
    }
    else
    {
        <title>WinApps</title>
    }


    @RenderSection("Head", required: false)
    @if (!IsSectionDefined("Head"))
    {
        <meta name="application-name" content="WinApps" />
        Html.RenderAction("FacebookTags", "Home");
    }

    @Styles.Render("~/content/css")

    @Scripts.Render("~/js")
    @Scripts.Render("~/js/modern")
</head>
<body class="modern-ui">

<div class="page">
	<div class="nav-bar">
		<div class="nav-bar-inner padding10">
			<span class="pull-menu"></span>

		    <a href="/">
		        <span class="element brand" >
		            <i class="fg-color-white icon-stats" style="font-size: 24px;"></i>
		            Win Apps <small>0.94</small>
		        </span>
		    </a>

			<div class="divider"></div>

		    <ul class="menu">
		        <li><a href="/">Home</a></li>
		        <li data-role="dropdown">
		            <a href="#">Top Apps</a>
		            <ul class="dropdown-menu">
		                <li>@Html.ActionLink("Recent", "Recent", "Apps")</li>
		                <li class="divider"></li>
		                <li>@Html.ActionLink("Top Games", "TopGames", "Apps")</li>
		                <li>@Html.ActionLink("Top Free Games", "TopFreeGames", "Apps")</li>
		                <li class="divider"></li>
		                <li>@Html.ActionLink("Top Apps", "TopApps", "Apps")</li>
		                <li>@Html.ActionLink("Top Free Apps", "TopFreeApps", "Apps")</li>
		            </ul>
		        </li>
                <li>@Html.ActionLink("Topics", "Topics", "Apps")</li>
                <li>@Html.ActionLink("Gone free", "GoneFree", "Apps")</li>

		        <li data-role="dropdown">
		            <a href="#">Browse</a>
		            <ul class="dropdown-menu">
		                <li>@Html.ActionLink("Games", "Search", "Apps", new { category = "Games" }, null)</li>
		                <li>@Html.ActionLink("Social", "Search", "Apps", new { category = "Social" }, null)</li>
		                <li>@Html.ActionLink("Photo", "Search", "Apps", new { category = "Photo" }, null)</li>
		                <li>@Html.ActionLink("Education", "Search", "Apps", new { category = "Education" }, null)</li>
		                <li class="divider"></li>
		                <li>@Html.ActionLink("All", "Search", "Apps")</li>
		            </ul>
		        </li>
		        <li data-role="dropdown"><a href="#">Stats</a>
		            <ul class="dropdown-menu">
		                <li>@Html.ActionLink("Overview", "Overview", "Stats")</li>
		                <li>@Html.ActionLink("Apps", "Apps", "Stats")</li>
		                <li>@Html.ActionLink("Developers", "Developers", "Stats")</li>
		            </ul>
		        </li>
		        <li data-role="dropdown"><a href="#">Info</a>
		            <ul class="dropdown-menu">
		                <li>@Html.ActionLink("About Us", "AboutUs", "Home")</li>
		                <li>@Html.ActionLink("Advertise", "Advertise", "Home")</li>
		                <li>@Html.ActionLink("Contact Us", "ContactUs", "Home")</li>
		            </ul>
		        </li>
				
			        
		    </ul>
		    <form action="@Url.Action("Search", "Apps")" method="GET" class="place-right">
                <div class="input-control text" style="margin-bottom: 0;">
                    <input type="text" name="query" />
                    <button class="btn-search"></button>
                </div>
            </form>
		</div>
	</div>
</div>
<div class="page" id="page-index">
    @RenderBody()
</div>
<div class="page">
	<div class="nav-bar">
		<div class="nav-bar-inner padding10">
		    <span class="element">
		        2013, WinApps &copy; by Itay Sagui and Ariel Ornstein
		    </span>
		    <span class="element place-right" style="margin: 0;">
		        <span id="social-share"></span>
		    </span>
		</div>
	</div>
</div>

    @RenderSection("Scripts", required: false)

    <script type="text/javascript">
        $('#social-share').share({
            networks: [
                'facebook',
                'pinterest',
                'googleplus',
                'twitter',
                'linkedin',
                'tumblr',
                'stumbleupon',
                'digg',
                'email'
            ],
            theme: 'square'
        });

    </script>

    <script type="text/javascript">
        var _gaq = _gaq || [];
        var pluginUrl = 
            '//www.google-analytics.com/plugins/ga/inpage_linkid.js';
        _gaq.push(['_require', 'inpage_linkid', pluginUrl]);

        _gaq.push(['_setAccount', 'UA-38227565-1']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
    </body>
</html>

Win8Apps/Views/shared/_alerts.cshtml
@using Win8Apps.BootstrapSupport
@if (TempData.ContainsKey(Alerts.ATTENTION))
{
    <div class="alert alert-block">
        <a class="close" data-dismiss="alert" href="#">x</a>
        <h4 class="alert-heading">Attention!</h4>
        @TempData[Alerts.ATTENTION]
    </div>
}
@foreach (string key in Alerts.ALL.Except(new[] { Alerts.ATTENTION }))
{
    if (TempData.ContainsKey(key))
    {
    <div class="alert alert-@key">
        <button type="button" class="close" data-dismiss="alert">x</button>
        @TempData[key]
    </div>
    }
}